package ConverterArea

object AreaTypes {
    const val icArea = "ar"
    const val icAcre = "ac"
    const val icCentimetro = "cm^2"
    const val icDecametro = "dkm^2"
    const val icDecimetro = "dm^2"
    const val icHectarea = "ha"
    const val icHectometro = "hm^2"
    const val icKilometro = "km^2"
    const val icMetro = "m^2"
    const val icMicrometro = "µm^2"
    const val icMilimetro = "mm^2"
    const val icMilla = "mi^2"
    const val icNanometro = "nm^2"
    const val icPie = "ft^2"
    const val icPulgada = "in^2"
    const val icYarda = "yd^2"

    const val nameArea = "Area"
    const val nameAcre = "Acre"
    const val nameCentimetro = "Centimetro"
    const val nameDecametro = "Decametro"
    const val nameDecimetro = "Decimetro"
    const val nameHectarea = "Hectarea"
    const val nameHectometro = "Hectometro"
    const val nameKilometro = "Kilometro"
    const val nameMetro = "Metro"
    const val nameMicrometro = "Micrometro"
    const val nameMilimetro = "Milimetro"
    const val nameMilla = "Milla"
    const val nameNanometro = "Nanometro"
    const val namePie = "Pie"
    const val namePulgada = "Pulgada"
    const val nameYarda = "Yarda"
}